// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "docproject",
    "version": "1"
  },
  "paths": {
    "/hello": {
      "post": {
        "summary": "hello",
        "description": "Post hello function",
        "tags": [
          "Hello from AutoSwagger"
        ],
        "operationId": "hello.post.hello",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Passenger"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "this went well",
            "schema": {
              "$ref": "#/definitions/Passenger"
            }
          },
          "400": {
            "description": "failed Post"
          },
          "502": {
            "description": "server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Passenger": {
      "properties": {
        "number": {
          "title": "Passenger.number",
          "type": "number"
        },
        "name": {
          "title": "Passenger.name",
          "type": "string"
        }
      },
      "required": [
        "number",
        "name"
      ],
      "additionalProperties": false,
      "title": "Passenger",
      "type": "object"
    }
  },
  "securityDefinitions": {}
};